// Curated pool of high-connectivity articles: reachable from almost anywhere.
export const TARGET_POOL: string[] = [
  "United States",
  "India",
  "World War II",
  "London",
  "Association football",
  "Music",
  "Science",
  "Mathematics",
  "English language",
  "Christianity",
  "France",
  "Germany",
  "China",
  "Japan",
  "United Kingdom",
  "Russia",
  "Canada",
  "Australia",
  "Italy",
  "Spain",
  "New York City",
  "Paris",
  "Islam",
  "Physics",
  "Chemistry",
  "Biology",
  "Philosophy",
  "History",
  "Film",
  "Television",
  "Latin",
  "Europe",
  "Asia",
  "Africa",
  "World War I",
  "Roman Empire",
  "Ancient Greece",
  "Democracy",
  "Economics",
  "Technology",
  "Internet",
  "Computer",
  "Olympic Games",
  "Basketball",
  "Book",
  "Language",
  "Religion",
  "Earth",
  "Sun",
  "Human",
];

export function pickTarget(exclude?: string): string {
  const pool = TARGET_POOL.filter((t) => t !== exclude);
  return pool[Math.floor(Math.random() * pool.length)];
}
